### ISSUE TITLE
Fails with Spring Boot 2.0M5

### ISSUE THREAD

**Issue by paulvi** [spring-guides/gs-actuator-service#16]
should be 
$ curl localhost:9001/health
{"status":"UP"}

is
http://localhost:9001/health
{
    "timestamp": 1508395012283,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/health"
}

Is this Spring Boot 2 issue?

**Comment by gregturn** [comment]
Actually, not the case. There are some big changes in Spring Boot 2 including actuator support. For instance, the path of the actuator endpoints is changed along with the need to activate the web-based actuator endpoints in the first place.

None of this is covered in the guides since they are coded for Boot 1.5 presently and we haven't scoped out efforts to upgrade them yet, which probably won't happen until Boot 2 reaches GA status.

**Comment by paulvi** [comment]
OK

**Comment by bclozel** [comment]
Fixed with #18
